"""Add student table and update days_of_week

Revision ID: fea5e9ebf158
Revises:
Create Date: 2026-08-11 15:50:45.254715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fea5e9ebf158'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_item')
    op.drop_table('program')
    op.drop_table('enrollment')
    op.drop_table('student')
    op.drop_table('swim_class')
    op.drop_index(op.f('uq_enrollment_student_class'), table_name='enrollment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('class_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('memo', mysql.TEXT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['swim_class.id'], name=op.f('enrollment_ibfk_2')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('enrollment_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_enrollment_student_class'), 'enrollment', ['student_id', 'class_id'], unique=True)
    op.create_table('swim_class',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('capacity', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('level', mysql.ENUM('BEGINNER', 'ELEMENTARY', 'INTERMEDIATE', 'ADVANCED', 'MASTER'), nullable=False),
    sa.Column('age_groups', mysql.ENUM('PRESCHOOL', 'ELEMENTARY', 'TEEN', 'ADULT', 'SENIOR'), nullable=False),
    sa.Column('goals', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('goal_etc', mysql.TEXT(), nullable=True),
    sa.Column('duration_min', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.TIME(), nullable=False),
    sa.Column('days_of_week', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('birth_year', sa.DATE(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('program_item',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('program_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phase', mysql.ENUM('WARM_UP', 'MAIN', 'COOL_DOWN'), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('detail', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('set', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('distance_m', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_min', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('is_checked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], name=op.f('program_item_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('program',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('status', mysql.ENUM('DRAFT', 'SCHEDULED', 'COMPLETED'), nullable=False),
    sa.Column('duration_min', mysql.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('equipment', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['swim_class.id'], name=op.f('program_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
