export type NavStackParamList = {
  AppSplash: undefined;
  ClassList: undefined;
  ClassRegister: undefined;
  ClassMember: undefined;
  ClassCreateComplete: undefined;
  LevelGuide: undefined;
  LessonPlanCreate: undefined;
  LessonPlanConfirm: undefined;
  LessonPlanComplete: undefined;
  LessonPlanEditItem: undefined;
  ClassListFilled: undefined;
  ClassDetailsLessonTab: undefined;
  ClassDetailsLessonTabScrollTest: undefined;
  ClassDetailsLessonTabDraft: undefined;
  ClassDetailsLessonTabEmpty: undefined;
  ClassDetailsLessonHistory: undefined;
  ClassDetailsInfoTab: undefined;
  ClassDetailsInfoEdit: undefined;
  ClassDetailsMemberTab: undefined;
  ClassDetailsMemberDetail: undefined;
  ClassDetailsMemberEdit: undefined;
  ClassDetailsReportTab: undefined;
  ClassDetailsReportSend: undefined;
  ClassDetailsReportHistory: undefined;
  WebReports: undefined;
};
