export type NavStackParamList = {
  ClassList: undefined;
  ClassRegister: undefined;
  ClassMember: undefined;
  ClassCreateComplete: undefined;
  LevelGuide: undefined;
  LessonPlanCreate: undefined;
  LessonPlanConfirm: undefined;
  LessonPlanComplete: undefined;
  LessonPlanEditItem: undefined;
  ClassListFilled: undefined;
  ClassDetailsLessonTab: undefined;
  ClassDetailsLessonTabEmpty: undefined;
  ClassDetailsLessonHistory: undefined;
  ClassDetailsInfoTab: undefined;
  ClassDetailsInfoEdit: undefined;
  ClassDetailsMemberTab: undefined;
  ClassDetailsMemberTabAdding: undefined;
  ClassDetailsMemberDetail: undefined;
  ClassDetailsMemberEdit: undefined;
};
